# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[47,)" #mandatory (33 is current forge version)
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="http://my.issue.tracker/" #optional
license = "MIT License"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId = "tofucraft" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version = "${file.jarVersion}" #mandatory
# A display name for the mod
displayName = "TofuCraftReload" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tofucraftreload" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "logo.png" #optional
# A text field displayed in the mod UI
credits = "iduki and turtton helping Revamped Content. 46mofu for add new texture. @siu_lab helping translation and making showcase! and Rutl-Tri made tofu world music! Also @MajinThorin753 make classic texture! and @uind_w helped Texture too! RizaSTAR helped new items! azzy helped new mob!" #optional
# A text field displayed in the mod UI
authors = "bagu_chan, 0999312" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''
TofuCraft in 1.20.1!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.tofucraft]] #optional
# the modid of the dependency
modId = "forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true #mandatory
# The version range of the dependency
versionRange = "[47.0.0,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"
# Here's another dependency
[[dependencies.tofucraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,]"
ordering = "NONE"
side = "BOTH"
[[dependencies.tofucraft]]
modId = "bagus_lib"
mandatory = true
versionRange = "[1.20.1-5.1.0,]"
ordering = "NONE"
side = "BOTH"
