package baguchan.tofucraft.client.animation.definitions;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class TofuGandlemAnimation {
	public static final AnimationDefinition ATTACK = AnimationDefinition.Builder.withLength(0.4f).addAnimation("undefined", new AnimationChannel(AnimationChannel.Targets.ROTATION, new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM), new Keyframe(0.12f, KeyframeAnimations.degreeVec(-108.5859725233563f, -7.520761628335549f, -21.267650873637194f), AnimationChannel.Interpolations.CATMULLROM), new Keyframe(0.24f, KeyframeAnimations.degreeVec(-31.090000000000003f, -7.52f, -21.27f), AnimationChannel.Interpolations.CATMULLROM), new Keyframe(0.36f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM))).build();
	public static final AnimationDefinition SHOOT = AnimationDefinition.Builder.withLength(2.08f).addAnimation("undefined", new AnimationChannel(AnimationChannel.Targets.ROTATION, new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM), new Keyframe(0.16f, KeyframeAnimations.degreeVec(-95f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM), new Keyframe(0.36f, KeyframeAnimations.degreeVec(-95f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM), new Keyframe(1.92f, KeyframeAnimations.degreeVec(-95f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM), new Keyframe(2.08f, KeyframeAnimations.degreeVec(0.0f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM))).addAnimation("undefined", new AnimationChannel(AnimationChannel.Targets.ROTATION, new Keyframe(0f, KeyframeAnimations.degreeVec(0.0f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM), new Keyframe(0.16f, KeyframeAnimations.degreeVec(57.5f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM), new Keyframe(1.92f, KeyframeAnimations.degreeVec(57.5f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM), new Keyframe(2.08f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM))).build();
	public static final AnimationDefinition SHOOTING = AnimationDefinition.Builder.withLength(0.24f).addAnimation("right_hand", new AnimationChannel(AnimationChannel.Targets.ROTATION, new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM), new Keyframe(0.12f, KeyframeAnimations.degreeVec(-95f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM), new Keyframe(0.24f, KeyframeAnimations.degreeVec(0.0f, 0f, 0f), AnimationChannel.Interpolations.CATMULLROM))).build();
}
